### ISSUE TITLE
Does not work on mac or linux.

### ISSUE THREAD

**Issue by tetra-fox** [tjhorner/dancing-ponies#5] opened 2015-07-11 02:52 UTC
@tjhorner #1 #4 #4 

- [ ] 

- 

`[1. ]([url](

**_## url_**

))`

**Comment by tjhorner** [comment] 2015-07-11 03:19
duplicate of #1

**Closed as completed by tjhorner** 2015-07-11 03:19 UTC
Labels: duplicate

**Comment by tetra-fox** [comment] 2015-07-11 04:19
oh .-.

**Comment by tjhorner** [comment] 2015-07-11 08:28
lol

**Comment by tetra-fox** [comment] 2017-11-12 23:07
Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.

**Comment by tjhorner** [comment] 2017-11-12 23:31
Fixed
